### ISSUE TITLE
Error message needed when ADB isn't exist under PATHs

### ISSUE THREAD

**Issue by Vdragon** [hucste/MTKZenyT#1]
Hi, it seems that a empty dialog is displayed when ADB is not exist under PATHs(I do installed Android SDK, but the platform-tools directory is currently not in $PATH.

It would be better if error message is printed.
![mtkzenyt bash konsole_616](https://cloud.githubusercontent.com/assets/1192163/8145205/5fed11c2-1231-11e5-8293-826101f1c01b.png)

**Comment by hucste** [comment]
Interesting! 
In fact, I forgot to translate a string. It's fixed with latest commit 3c7d219759...
